# This file was generated by nuget-to-nix.
# Regenerate with: nix run nixpkgs#nuget-to-nix -- deps.nix
#
# Placeholder — run the generator on a Linux machine with .NET SDK 10
# to populate the actual dependency hashes.
{ fetchurl }: [
]
