services:
  db:
    image: pgvector/pgvector:pg18-trixie
    container_name: sharpclaw-db
    environment:
      POSTGRES_DB: sharpclaw
      POSTGRES_USER: sharpclaw
      POSTGRES_PASSWORD: sharpclaw
#    uncomment this to expose the database
#    ports:
#      - "5532:5432"
    volumes:
      - sharpclaw-pg-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sharpclaw -d sharpclaw"]
      interval: 5s
      timeout: 5s
      retries: 20

  ollama:
    image: alpine/ollama
    container_name: sharpclaw-ollama
    restart: unless-stopped
#    ports:
#      - "21434:11434"
    volumes:
      - sharpclaw-ollama-data:/root/.ollama

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ""
    container_name: sharpclaw-app
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__sharpclaw: Host=db;Port=5432;Database=sharpclaw;Username=sharpclaw;Password=sharpclaw
      LmStudio__Endpoint: 'http://172.17.240.1:11434/v1/'
      LmStudio__ApiKey: 'ollama'
      LmStudio__EmbeddingEndpoint: 'http://ollama:11434'
      LmStudio__EmbeddingApiKey: 'ollama'
      LmStudio__EmbeddingModel: 'qwen3-embedding:0.6b'
#      LmStudio__EmbeddingModel: 'embeddinggemma:300m'
      LmStudio__EmbeddingProvider: 'LocalOllama'
      LmStudio__EmbeddingTimeout: 60
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    ports:
      - "5846:8080"
    restart: unless-stopped

volumes:
  sharpclaw-pg-data:
  sharpclaw-ollama-data: